tiramisu:
    tiramisu_path: "/scratch/dl5133/Env/tiramisu" 
    env_type:  "model"
    tags_model: "/scratch/dl5133/Dev/RL-Agent/tiramisu-env/env_api/scheduler/models/model_release_version.pt"

dataset:
    path: '/scratch/dl5133/Dev/RL-Agent/rl_autoscheduler/utils/program_generator/Dataset_multi/'
    offline : '/scratch/dl5133/Dev/RL-Agent/tiramisu-env/legal_actions.pkl'
